### ISSUE TITLE
Dev container does not launch on ARM mac

### ISSUE THREAD

**Issue by juho** [AxisCommunications/acap-rs#51]
The dev container fails to launch with the error `[qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory]` on an ARM-based mac.

You can add `--platform=linux/amd64` to the `FROM` statements to overcome this, but seems kinda hacky.

**Comment by apljungquist** [comment]
Hey Juho,

Thank you for taking time to bring this to my attention. I will look into it but I don't an ARM-based computer at hand, so it will take some time. In the meanwhile, feel free to open a PR with the hacky solution; I think it sounds reasonable so as long as it doesn't break the systems I test on I will be happily accept it.

In case you missed it, I see some people suggesting setting `--platform` in [`runArgs`](https://containers.dev/implementors/json_reference/#image-specific), but I don't know enough about multi-platform containers and dev containers to say if this is less hacky, or if it will even work.

**Comment by apljungquist** [comment]
I made a brief attempt at reproducing this on a `macos-14` runner, which seems to be arm64 based since it uses M1[^1]; Colima seems like the way to go, but does not start[^3] and steps that have helped others run docker-proper fail for me[^2].

[^1]: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for--private-repositories
[^2]: The steps suggested in [actions/runner#1456](https://github.com/actions/runner/issues/1456) fail with `sudo: /Applications/Docker.app/Contents/MacOS/Docker: command not found`
[^3]: This is apparently a [known issue](https://github.com/abiosoft/colima/issues/1023).

**Comment by juho** [comment]
Yeah, looking around I'm a little confused what the real solution would be either. I think the `--platform` arg might be the cleanest?

**Comment by apljungquist** [comment]
If it works, then I think it is an improvement over status quo, and I don't think either increases the entropy more than the other. If you do experiment with more than one solution, I' want to share in your learnings so feel free to write a long comment or commit message :nerd_face:

**Comment by juho** [comment]
I tried with the `--platform` arg, and it didn't take hold for some reason. The only way I've had it working so far is to explicitly set the `FROM` arch. A little puzzled.

**Comment by apljungquist** [comment]
Thanks for taking time to test the project and help fix this problem. Please don't hesitate to reach out with any other questions or suggestions.

**Comment by juho** [comment]
Yeah we're building an actual app with it, so far so good- this was running custom stuff in the camera after 15 minutes versus a day fighting with the C++ SDK, so please keep this up :)
