### ISSUE TITLE
Update to Rustc 1.80.0

### ISSUE THREAD

**Issue by juho** [AxisCommunications/acap-rs#98]
Some packages require 1.80.0, it would be nice to update the toolchain at least to it

**Comment by apljungquist** [comment]
I don't see why not. Do you happen to remember which package and/or the error message?

Feel free to submit a PR. Otherwise I will do it once I finish my current experiment with reproducible builds.

**Comment by juho** [comment]
Cool, orion at least was complaining for me, giving the "this requires 1.80.0" message

**Comment by apljungquist** [comment]
As I think more about it I wonder why you are restricted by the tool-chain version that is currently specified in this project?

My idea was that users would either:

1. Use `acap-rs-app-template` as a template for a new git repository and install tools and libraries from crates.io (only applicable for `acap-logging` so far), or directly from this repository. This would be the preferred way since everyone benefits from improvements made to upstream.
2. Fork `acap-rs` (this repository) and customize the tooling for their specific needs.

**Comment by juho** [comment]
Fair question, mostly cuz I was being dumb and developing in a fork of this repo instead of the template :)

**Comment by apljungquist** [comment]
Not dumb, I would probably do the same since there is a lot more scaffolding in this repository that aligns with how I want my projects to be set up (duh :upside_down_face:). Was there anything in particular that made starting from this repository, rather than the template, attractive to you?
